venv\Scripts\python.exe -m pip install --upgrade pyinstaller
venv\Scripts\python.exe -m pip install --upgrade pywin32
venv\Scripts\python.exe -m pip install --upgrade python-telegram-bot
venv\Scripts\python.exe -m pip install --upgrade PyAutoGUI
venv\Scripts\python.exe -m pip install --upgrade PyScreeze
venv\Scripts\python.exe -m pip install --upgrade pywinauto
venv\Scripts\python.exe -m pip install --upgrade opencv-python
venv\Scripts\python.exe -m pip install --upgrade pywin32-ctypes
venv\Scripts\python.exe -m pip install --upgrade python-dateutil
venv\Scripts\python.exe -m pip install --upgrade openpyxl
venv\Scripts\python.exe -m pip install --upgrade xlrd
venv\Scripts\python.exe -m pip install --upgrade xlwt
venv\Scripts\python.exe -m pip install --upgrade pytesseract